# Generated by Django 4.2 on 2023-04-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movies",
            name="synopsis",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="movies",
            name="rating",
            field=models.CharField(
                choices=[
                    ("G", "G"),
                    ("PG", "Pg"),
                    ("PG-13", "Pg 13"),
                    ("R", "R"),
                    ("NC-17", "Nc 17"),
                ],
                default="G",
                max_length=20,
                null=True,
            ),
        ),
    ]
