# Generated by Django 4.2 on 2023-04-16 15:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movies", "0002_movies_synopsis_alter_movies_rating"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Movies",
            new_name="Movie",
        ),
    ]
